// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWROpwHPxIEPyQAIA3VmBbb8jpJyTLWAI',
    appId: '1:1092013916238:web:0f12af47cec47d289c431f',
    messagingSenderId: '1092013916238',
    projectId: 'smilestoneuser',
    authDomain: 'smilestoneuser.firebaseapp.com',
    databaseURL: 'https://smilestoneuser-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smilestoneuser.firebasestorage.app',
    measurementId: 'G-7R4S0QYCF3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAz3meeLtKYkagNpCRiEmqrpz8eHuDuvi8',
    appId: '1:1092013916238:android:1d94607db06bf7ab9c431f',
    messagingSenderId: '1092013916238',
    projectId: 'smilestoneuser',
    databaseURL: 'https://smilestoneuser-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smilestoneuser.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAuG0D7XhrDBWf9rZoc-qDwIpAvhKqTE_0',
    appId: '1:1092013916238:ios:adeada575c18e8559c431f',
    messagingSenderId: '1092013916238',
    projectId: 'smilestoneuser',
    databaseURL: 'https://smilestoneuser-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smilestoneuser.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAuG0D7XhrDBWf9rZoc-qDwIpAvhKqTE_0',
    appId: '1:1092013916238:ios:adeada575c18e8559c431f',
    messagingSenderId: '1092013916238',
    projectId: 'smilestoneuser',
    databaseURL: 'https://smilestoneuser-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smilestoneuser.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDWROpwHPxIEPyQAIA3VmBbb8jpJyTLWAI',
    appId: '1:1092013916238:web:39381a14558caed49c431f',
    messagingSenderId: '1092013916238',
    projectId: 'smilestoneuser',
    authDomain: 'smilestoneuser.firebaseapp.com',
    databaseURL: 'https://smilestoneuser-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smilestoneuser.firebasestorage.app',
    measurementId: 'G-WCDPSVYM5H',
  );
}
